# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java Cl with Maven
push:
branches: [ "main"]
pull_request:
branches ["main"]

jobs:
get-info:
runs-on: ubuntu-latest
steps:
- run: echo "T his jobs were automatically triggered by a ${{ github.event_name event on ${{ github.repository )}!!!" ! "
bu ild:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- name: Set up JDK I I
uses: actions/setup-java@v3
java-version: 'l l'
distribution: 'temurin'
- name: Build with Maven
run: mvn -B package —file porn.xml
test:
runs-on: ubuntu-latest
steps:
- name: Checkout the repository
uses: actions/checkout@v2
- name: Set up JDK 14
uses: actions/setup-java@v I
java-version: 14
- name: Run tests with Maven
run: mvn -B test --file pom.xml
